#!/usr/bin/env bash
set -euo pipefail

IN_CONTAINER=false
if [[ "${DEVPOD:-}" == "true" || "${CODESPACES:-}" == "true" || "${REMOTE_CONTAINERS:-}" == "true" ]]; then
  IN_CONTAINER=true
fi

if ! command -v cz >/dev/null 2>&1 && [[ "$IN_CONTAINER" == "true" ]]; then
  git config --global push.autoSetupRemote true
  git config --global --add safe.directory /workspaces/devops-masterclass/

  python3 -m pip install --user pipx
  python3 -m pipx ensurepath
  export PATH="$HOME/.local/bin:$PATH"

  pipx install commitizen

  pre-commit install
  pre-commit install --hook-type commit-msg
fi